-- Insert data into Supabase tables based on current Firebase export
-- Run these commands after creating the schema

-- Insert Academic Projects
INSERT INTO academic_projects (role, company, date, description, link, image, technologies) VALUES
('Researcher', 'A Personalized Spatiotemporal Human Activity Recognition Framework in an Edge-Based Federated Learning Approach', 'Academic Research', 'Drafted an IEEE-format paper analyzing prior research on human activity recognition, federated learning, edge computing, and spatiotemporal data. Proposed a framework integrating spatiotemporal data into a human activity recognition system using edge-based federated learning, supported by a detailed presentation.', '#', '/images/projects/har-federated.png', ARRAY['Mendeley', 'Google Scholar', 'Microsoft Word', 'Microsoft PowerPoint']),
('Researcher', 'Salary Data Prediction and Analysis Using Machine Learning', 'GitHub', 'Developed a predictive model for tech employee salaries using four years of Stack Overflow data. Implemented and compared ML models (Linear Regression, Decision Tree, Random Forest, Gradient Boosting, XGBoost) using MAE, MSE, and R² metrics. Integrated the model into production for real-time predictions via Streamlit and visualized salary trends pre- and post-pandemic with Matplotlib, supported by detailed documentation.', 'https://github.com/wafafatima66/Prediction-analysis-ML', '/images/projects/salary-prediction.png', ARRAY['Python', 'Matplotlib', 'Numpy', 'Pandas', 'Pickle', 'Sklearn', 'Streamlit', 'Git', 'Jupyter Notebook']),
('Researcher', 'Cognitive Science and Artificial Intelligence', 'Academic Research', 'Authored an APA-format literature review on AI creativity, rationality, and theory of mind, synthesizing research, assessing methodologies, and identifying gaps in the field.', '#', '/images/projects/cognitive-ai.png', ARRAY['APA Style', 'Google Scholar', 'Microsoft Word']);

-- Insert Projects (Work Projects)
INSERT INTO projects (role, company, date, description, long_description, basic_info, link, image, technologies, featured, theme, casestudy_images) VALUES
('Full Stack Developer', 'BerriesHut (E-commerce Site)', 'GitHub', 'Designed and developed a fully functional e-commerce site, enhancing user experience and streamlining online transactions.', NULL, NULL, 'https://github.com/wafafatima66/berrieshut', 'berrieshut.png', ARRAY['WordPress', 'WooCommerce'], FALSE, NULL, NULL),
('Developer', 'Tweety (Twitter Clone)', 'GitHub', 'Developed a Twitter clone replicating user profiles, tweeting, following, and real-time updates for enhanced social interaction.', NULL, NULL, 'https://github.com/wafafatima66/tweety', 'twitter-laravel.png', ARRAY['Laravel', 'Tailwind'], FALSE, NULL, NULL),
('Game Developer', 'Rock Scissor Paper Game', 'GitHub', 'Created an interactive Rock, Paper, Scissors game with engaging UI, real-time gameplay, and a dynamic scoring system.', NULL, NULL, 'https://github.com/wafafatima66/rock-paper-scissor', 'rock-js.png', ARRAY['JavaScript'], FALSE, NULL, NULL),
('Game Developer', 'Rock Scissor Paper & Quiz Game', 'GitHub', 'Extended Rock, Paper, Scissors with a quiz feature, combining entertainment with learning through an interactive interface.', NULL, NULL, 'https://github.com/wafafatima66/rock-paper-scissor-quiz-app-python', 'rock-python.png', ARRAY['Python'], FALSE, NULL, NULL),
('Backend Developer', 'Minimal E-commerce Website', 'GitHub', 'Developed a chatbot app with Node.js, Express, and MongoDB. Messages are stored in MongoDB, demonstrating full-stack development basics.', NULL, NULL, 'https://github.com/wafafatima66/furniture-website-html-nodejs', 'furniture-website-nodejs.png', ARRAY['Node.js', 'Express', 'MongoDB'], FALSE, NULL, NULL),
('ML Developer', 'Tech Employee Salary Prediction', 'GitHub', 'Predictive modeling project that estimates tech employee salaries using Stack Overflow survey data from four consecutive years. The project leverages multiple machine learning models, performs comparative analysis, and integrates the best model into a real-time web app for salary prediction.', NULL, NULL, 'https://github.com/wafafatima66/salary_prediction_visualization-python', 'salary-prediction-ml.png', ARRAY['Python', 'Matplotlib', 'Numpy', 'Pandas', 'Pickle', 'Scikit-learn', 'Streamlit'], FALSE, NULL, NULL),
('Frontend Developer', 'Notes Management System', 'GitHub', 'A full-featured Notes Management System (CMS) built with Laravel. This CMS allows administrators to manage pages, posts, users, categories, and more, all from a clean and responsive dashboard interface.', 'The Notes Management System (CMS) is a comprehensive, full-featured application built with Laravel, designed to streamline content management for administrators and teams. It provides a centralized and intuitive dashboard where users can efficiently manage pages, posts, categories, and user roles, ensuring seamless workflow and organization. The system incorporates robust user authentication and role-based access control, allowing different levels of permissions for administrators, editors, and contributors. Content creation is made easy and flexible with the integrated rich text editor (CKEditor), supporting formatted text, media, and embedded elements. Posts can be organized with categories and tags, while dynamic page creation and built-in SEO support ensure that content is optimized for search engines. The application follows a clean MVC architecture and RESTful routing, maintaining a scalable and maintainable codebase that can adapt to future feature expansions and integrations. This CMS not only simplifies content management but also enhances productivity and operational efficiency for teams managing large volumes of notes and posts.', '*Project Duration:* 3 Months  \n*Role:* Frontend Developer & API Integration  \n*Project Type:*  Client Project (Team Collaboration)  \n*Wireframe:*  Designed by me', 'https://github.com/wafafatima66/notes-management-system-laravel', 'notes-management.png', ARRAY['Laravel', 'Mysql', 'JavaScript', 'Bootstrap'], TRUE, '#4f6597', NULL),
('Full-Stack Developer', 'HR Management System', 'GitHub', 'This is a full-featured Human Resource Management System built using raw PHP and MySQL. It supports multiple user roles and comprehensive modules for managing employees, performance, leaves, and more.', 'I developed a full-featured Human Resource Management System (HRMS) for a client project that spanned three years, handling the frontend, backend, database, and deployment as a solo developer. Built using raw PHP and MySQL, the system supports multiple user roles—including Super Administrators, Agency Heads, Division Heads, and Employees—and provides comprehensive modules for employee management, leave tracking, performance evaluation, learning and development, hiring, and report generation. The project was based on client-provided wireframes, and I was responsible for debugging, performance optimization, API integration, and feature enhancements such as dynamic dashboards and advanced reporting tools. The system streamlines HR processes, improves efficiency, and delivers accurate, real-time insights, offering a robust solution for managing employees, performance, and organizational data', '*Project Duration:* 3 Years  \n\n*Role:* Full-Stack Developer (Frontend, Backend, Database, Deployment)  \n\n*Project Type:* Solo client project  \n\n*Wireframe Provided By:* Client  \n', 'https://github.com/wafafatima66/Human-resourse-management-system-php-mysql', 'hr-system-php.png', ARRAY['PHP', 'Bootstrap', 'JavaScript', 'Jquery', 'Ajax', 'Mysql'], TRUE, '#FC7E43', ARRAY['hr2.png', 'hr3.png', 'hr4.png', 'hr5.png', 'hr6.png', 'hr7.png']),
('Developer', 'Admin Dashboard', 'GitHub', 'This is a robust, extendable Admin Dashboard built with Laravel. It provides comprehensive administrative features including user management, support ticket handling, system-wide settings, and notification broadcasting.', NULL, NULL, 'https://github.com/wafafatima66/admin-dashboard-advanced-laravel-bootstrap', 'admin-laravel.png', ARRAY['Laravel', 'Bootstrap ', 'Jquery', 'MySql', 'JavaScript'], FALSE, NULL, NULL),
('Developer', 'Hotel Landing Page', 'GitHub', 'A responsive, modern personal hotel landing page website built entirely using raw HTML and CSS, with no frameworks.', NULL, NULL, 'https://github.com/wafafatima66/hotel-theme-html-css', 'hotel-landing-html.png', ARRAY['HTML', 'CSS', 'Bootstrap'], FALSE, NULL, NULL),
('Developer', 'E-commerce Website', 'GitHub', 'BERRIESHUT is a premium WordPress ecommerce website built with Elementor, specializing in various  products. Our platform offers customers a delightful shopping experience with intuitive navigation and mouth-watering product displays.', NULL, NULL, NULL, 'berrieshut.png', ARRAY['Wordpress', 'Woocommerce', 'Elementor'], FALSE, NULL, NULL);

-- Insert Testimonials
INSERT INTO testimonials (name, title, text, image) VALUES
('James Carter', 'CTO at TechWave', 'Fatima delivered high-quality solutions on time and demonstrated strong problem-solving skills throughout the project.', 'https://i.pravatar.cc/150?img=12'),
('Alicia Gomez', 'Project Manager at Docua', 'Her expertise in software development and teamwork made a huge difference in the successful launch of our product.', 'https://i.pravatar.cc/150?img=36'),
('Robert Wilson', 'Business Owner', 'The e-commerce website she developed boosted our sales by improving user experience and system efficiency.', 'https://i.pravatar.cc/150?img=18'),
('Sophia Lee', 'Research Collaborator', 'Her work on machine learning models showed exceptional technical depth and attention to detail.', 'https://i.pravatar.cc/150?img=52');

-- Insert About Me
INSERT INTO about_me (biography, services, contact_email, profile_image) VALUES
('I am a versatile software engineer with experience as a developer, project manager, and researcher. As a developer, I have built full-stack web applications, machine learning models, and e-commerce platforms using tools like Laravel, React.js, TensorFlow, and WordPress. My project management work includes leading cross-functional teams to deliver high-performing websites and resolving complex technical issues to optimize performance and user experience. As a researcher, I have explored federated learning, edge computing, and human activity recognition, drafting IEEE-format papers and presenting innovative frameworks. This blend of skills allows me to bridge technical execution, strategic planning, and innovative problem-solving.', '* Software Development\n* Machine Learning & Data Analysis\n* Project Management\n* WordPress & E-commerce Solutions\n* Research & Technical Writing', 'fatima.amir.dev@gmail.com', '/your-photo.png');

-- Insert Stats
INSERT INTO stats (heading, value) VALUES
('Years of Experience', '5+'),
('Projects Done', '30+');

-- Insert Academic Background
INSERT INTO academic_background (title, institution, type, text, result, order_sequence) VALUES
('MSc in Computer Science and Engineering', 'Military Institute of Science and Technology', 'Education', 'Focused on advanced machine learning, artificial intelligence, and data-driven solutions while gaining practical experience in research and applied computer science.', 'On Going', 4),
('BSc in Computer Science and Engineering', 'Shanto Mariam University of Creative Technology', 'Education', 'Gained a strong foundation in software development, algorithms, database systems, and programming across multiple languages.', '3.96/4.00', 3),
('IELTS', 'IDP', 'Standardized Exam', '7.5/9', NULL, NULL),
('GRE', 'ETS', 'Standardized Exam', '289/340', NULL, NULL),
('12th - CBSE', 'New Indian Model School, Sharjah, U.A.E', 'Education', '89%', NULL, 2),
('10th CBSE', 'New Indian Model School , Sharjah ', 'Education', '10/10', NULL, 1);

-- Insert Timeline Data
INSERT INTO timeline_data (date, title, location, description, link, sequence_order) VALUES
('Mar 2025 - Present', 'Project Manager', 'Loud Spectrum, CA, USA (Remote)', 'Manage development, marketing, and design teams using ClickUp to coordinate tasks and ensure timely delivery. Communicate with clients to gather requirements, translate them into actionable plans, and oversee projects from planning to completion, ensuring quality outcomes and alignment with business goals.', 'https://loudspectrum.com/en', 6),
('Aug 2022 - Feb 2025', 'WordPress Developer | Project Manager', 'Medical Terpenes, CA, USA (Remote)', 'Resolved 200+ WordPress issues through plugin and theme customization, boosting traffic by 60% and improving site performance on mobile and desktop. As Project Manager, led an 8-member team to design and develop a high-performing eCommerce website using the latest trends and strategies.', 'http://medicalterpenes.com/', 5),
('Feb 2022 - Jun 2022', 'Software Developer', 'Docua, Japan (Remote)', 'Developed a note management system with Laravel and API testing via Postman, increasing efficiency by 60%. Also authored the user manual and conducted QA testing.', '#', 4),
('Nov 2020 - Jan 2022', 'PHP Developer', 'Nitibdev IT Solutions, Philippines (Remote)', 'Designed and deployed an HR Management System using LAMP stack, reducing manual input by 80% and boosting efficiency by 50%.', '#', 3),
('Feb 2020 - Mar 2020', 'Web Developer', 'UMSTDL, Dhaka, Remote', 'Solely responsible for designing, deploying, and ensuring the software quality for educational institutions, delivering a reliable and efficient solution tailored to their needs', NULL, 2);

-- Insert Technologies
INSERT INTO technologies (name, experience, duration, icon) VALUES
('Python', 90, 4, NULL),
('TensorFlow', 15, 3, NULL),
('JavaScript', 80, 3, NULL),
('Laravel', 75, 2, NULL),
('React', 50, 2, NULL),
('WordPress', 75, 3, NULL),
('PHP', 90, 4, NULL),
('Tailwind CSS', 80, 2, NULL),
('MySQL', 75, 3, NULL),
('Next.js', 45, 5, NULL),
('Firebase', 45, 3, NULL);

-- Insert Courses
INSERT INTO courses (name, institution, year, description, skills) VALUES
('IBM DevOps and Software Engineering Professional Certificate', 'Coursera', '2025', 'Learned continuous integration, deployment, monitoring, and cloud-based DevOps workflows to streamline development pipelines.', 'Continuous Integration, Application Deployment, Application Deployment, Linux Commands, DevOps, Cloud Computing Architecture, Software Development Life Cycle,  Jupyter,Git (Version Control System),Software Architecture,Agile Software Development,Test Driven Development (TDD)'),
('Python for Everybody', 'Free Code Camp', '2023', 'Mastered Python fundamentals, data handling, web scraping, and API interaction for real-world problem solving.', NULL),
('IBM Full Stack Software Developer', 'Coursera', '2025', 'Build full stack cloud apps with modern front-end, back-end, and cloud-native tools, and showcase skills through projects and a capstone on GitHub.', 'Application Deployment,Application Design,Cloud Computing Architecture,Software Development Life Cycle,Jupyter,Git (Version Control System),Cloud Computing,Software Architecture,Kubernetes,Django (Web Framework),Node.JS,Cloud Services');